DROP DATABASE IF EXISTS `scope`;
CREATE DATABASE `scope` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `scope`;
DROP TABLE IF EXISTS `accounts`;
CREATE TABLE `accounts` (
  `username` varchar(20) COLLATE latin1_bin NOT NULL,
  `passwd` longtext COLLATE latin1_bin NOT NULL,
  `rolename` varchar(255) COLLATE latin1_bin NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin ROW_FORMAT=COMPACT;

DROP TABLE IF EXISTS `acquisition`;
CREATE TABLE `acquisition` (
  `ID` varchar(255) NOT NULL,
  `chamber` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `color` varchar(255) DEFAULT NULL,
  `scale` double(30,2) DEFAULT NULL,
  `route` varchar(255) DEFAULT NULL,
  `isda` int(1) DEFAULT NULL,
  `value` mediumtext,
  PRIMARY KEY (`ID`,`chamber`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

DROP TABLE IF EXISTS `alarmlog`;
CREATE TABLE `alarmlog` (
  `idx` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` longtext NOT NULL,
  `id` int(11) DEFAULT NULL,
  `severity` longtext NOT NULL,
  `message` longtext,
  `description` longtext,
  `poster` longtext,
  `posttime` datetime NOT NULL,
  `recovtype` longtext,
  `recovtime` datetime DEFAULT NULL,
  `recovactor` longtext,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

DROP TABLE IF EXISTS `awc`;
CREATE TABLE `awc` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `time` text,
  `device` text,
  `source` text,
  `chamber` text,
  `lotid` text,
  `matname` text,
  `arm` text,
  `action` text,
  `offset` text,
  `roffset` double DEFAULT NULL,
  `toffset` double DEFAULT NULL,
  `r` double DEFAULT NULL,
  `t` double DEFAULT NULL,
  `x` double DEFAULT NULL,
  `y` double DEFAULT NULL,
  `deviation` double DEFAULT NULL,
  `matsize` int(11) DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ch2`;
CREATE TABLE `ch2` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `LotID` text,
  `MaterialName` text,
  `RecipeName` text,
  `RcpTotalStep` int(11) DEFAULT NULL,
  `RcpStepCounter` int(11) DEFAULT NULL,
  `RcpStepName` text,
  `RcpStepTime` double DEFAULT NULL,
  `RcpStepStartTime` text,
  `RcpStepElapsedTime` double DEFAULT NULL,
  `PedControlAIMin` double DEFAULT NULL,
  `PedControlAIMax` double DEFAULT NULL,
  `PedControlAIAvg` double DEFAULT NULL,
  `PedControlAIStd` double DEFAULT NULL,
  `PedControlAI` text,
  `PedControlAITimes` text,
  `PedControlAITSN` int(11) DEFAULT NULL,
  `PedControlAIBSN` int(11) DEFAULT NULL,
  `PedMonitorAIMin` double DEFAULT NULL,
  `PedMonitorAIMax` double DEFAULT NULL,
  `PedMonitorAIAvg` double DEFAULT NULL,
  `PedMonitorAIStd` double DEFAULT NULL,
  `PedMonitorAI` text,
  `PedMonitorAITimes` text,
  `PedMonitorAITSN` int(11) DEFAULT NULL,
  `PedMonitorAIBSN` int(11) DEFAULT NULL,
  `BSPMin` double DEFAULT NULL,
  `BSPMax` double DEFAULT NULL,
  `BSPAvg` double DEFAULT NULL,
  `BSPStd` double DEFAULT NULL,
  `BSP` text,
  `BSPTimes` text,
  `BSPTSN` int(11) DEFAULT NULL,
  `BSPBSN` int(11) DEFAULT NULL,
  `BSFMin` double DEFAULT NULL,
  `BSFMax` double DEFAULT NULL,
  `BSFAvg` double DEFAULT NULL,
  `BSFStd` double DEFAULT NULL,
  `BSF` text,
  `BSFTimes` text,
  `BSFTSN` int(11) DEFAULT NULL,
  `BSFBSN` int(11) DEFAULT NULL,
  `BSPSetValueMin` double DEFAULT NULL,
  `BSPSetValueMax` double DEFAULT NULL,
  `BSPSetValueAvg` double DEFAULT NULL,
  `BSPSetValueStd` double DEFAULT NULL,
  `BSPSetValue` text,
  `BSPSetValueTimes` text,
  `BSPSetValueTSN` int(11) DEFAULT NULL,
  `BSPSetValueBSN` int(11) DEFAULT NULL,
  `ForelineMin` double DEFAULT NULL,
  `ForelineMax` double DEFAULT NULL,
  `ForelineAvg` double DEFAULT NULL,
  `ForelineStd` double DEFAULT NULL,
  `Foreline` text,
  `ForelineTimes` text,
  `ForelineTSN` int(11) DEFAULT NULL,
  `ForelineBSN` int(11) DEFAULT NULL,
  `O2Min` double DEFAULT NULL,
  `O2Max` double DEFAULT NULL,
  `O2Avg` double DEFAULT NULL,
  `O2Std` double DEFAULT NULL,
  `O2` text,
  `O2Times` text,
  `O2TSN` int(11) DEFAULT NULL,
  `O2BSN` int(11) DEFAULT NULL,
  `Ar2Min` double DEFAULT NULL,
  `Ar2Max` double DEFAULT NULL,
  `Ar2Avg` double DEFAULT NULL,
  `Ar2Std` double DEFAULT NULL,
  `Ar2` text,
  `Ar2Times` text,
  `Ar2TSN` int(11) DEFAULT NULL,
  `Ar2BSN` int(11) DEFAULT NULL,
  `H2Min` double DEFAULT NULL,
  `PedPosMax` double DEFAULT NULL,
  `H2Max` double DEFAULT NULL,
  `H2Avg` double DEFAULT NULL,
  `H2Std` double DEFAULT NULL,
  `H2` text,
  `H2Times` text,
  `H2TSN` int(11) DEFAULT NULL,
  `H2BSN` int(11) DEFAULT NULL,
  `H2EPMin` double DEFAULT NULL,
  `H2EPMax` double DEFAULT NULL,
  `H2EPAvg` double DEFAULT NULL,
  `H2EPStd` double DEFAULT NULL,
  `H2EP` text,
  `H2EPTimes` text,
  `H2EPTSN` int(11) DEFAULT NULL,
  `H2EPBSN` int(11) DEFAULT NULL,
  `ArBPMin` double DEFAULT NULL,
  `ArBPMax` double DEFAULT NULL,
  `ArBPAvg` double DEFAULT NULL,
  `ArBPStd` double DEFAULT NULL,
  `ArBP` text,
  `ArBPTimes` text,
  `ArBPTSN` int(11) DEFAULT NULL,
  `ArBPBSN` int(11) DEFAULT NULL,
  `ArEPMin` double DEFAULT NULL,
  `ArEPMax` double DEFAULT NULL,
  `ArEPAvg` double DEFAULT NULL,
  `ArEPStd` double DEFAULT NULL,
  `ArEP` text,
  `ArEPTimes` text,
  `ArEPTSN` int(11) DEFAULT NULL,
  `ArEPBSN` int(11) DEFAULT NULL,
  `ArSPMin` double DEFAULT NULL,
  `ArSPMax` double DEFAULT NULL,
  `ArSPAvg` double DEFAULT NULL,
  `ArSPStd` double DEFAULT NULL,
  `ArSP` text,
  `ArSPTimes` text,
  `ArSPTSN` int(11) DEFAULT NULL,
  `ArSPBSN` int(11) DEFAULT NULL,
  `TVPressureMin` double DEFAULT NULL,
  `TVPressureMax` double DEFAULT NULL,
  `TVPressureAvg` double DEFAULT NULL,
  `TVPressureStd` double DEFAULT NULL,
  `TVPressure` text,
  `TVPressureTimes` text,
  `TVPressureTSN` int(11) DEFAULT NULL,
  `TVPressureBSN` int(11) DEFAULT NULL,
  `TVAnglePosMin` double DEFAULT NULL,
  `TVAnglePosMax` double DEFAULT NULL,
  `TVAnglePosAvg` double DEFAULT NULL,
  `TVAnglePosStd` double DEFAULT NULL,
  `TVAnglePos` text,
  `TVAnglePosTimes` text,
  `TVAnglePosTSN` int(11) DEFAULT NULL,
  `TVAnglePosBSN` int(11) DEFAULT NULL,
  `WaferCounterMin` double DEFAULT NULL,
  `WaferCounterMax` double DEFAULT NULL,
  `WaferCounterAvg` double DEFAULT NULL,
  `WaferCounterStd` double DEFAULT NULL,
  `WaferCounter` text,
  `WaferCounterTimes` text,
  `WaferCounterTSN` int(11) DEFAULT NULL,
  `WaferCounterBSN` int(11) DEFAULT NULL,
  `PedPosMin` double DEFAULT NULL,
  `PedPosAvg` double DEFAULT NULL,
  `PedPos` text,
  `PedPosStd` double DEFAULT NULL,
  `PedPosTimes` text,
  `PedPosTSN` int(11) DEFAULT NULL,
  `PedPosBSN` int(11) DEFAULT NULL,
  `BiasRFForwardPowerMin` double DEFAULT NULL,
  `BiasRFForwardPowerMax` double DEFAULT NULL,
  `BiasRFForwardPowerAvg` double DEFAULT NULL,
  `BiasRFForwardPowerStd` double DEFAULT NULL,
  `BiasRFForwardPower` text,
  `BiasRFForwardPowerTimes` text,
  `BiasRFForwardPowerTSN` int(11) DEFAULT NULL,
  `BiasRFForwardPowerBSN` int(11) DEFAULT NULL,
  `BiasRFReflectedPowerMin` double DEFAULT NULL,
  `BiasRFReflectedPowerMax` double DEFAULT NULL,
  `BiasRFReflectedPowerAvg` double DEFAULT NULL,
  `BiasRFReflectedPowerStd` double DEFAULT NULL,
  `BiasRFReflectedPower` text,
  `BiasRFReflectedPowerTimes` text,
  `BiasRFReflectedPowerTSN` int(11) DEFAULT NULL,
  `BiasRFReflectedPowerBSN` int(11) DEFAULT NULL,
  `BiasC1PosMin` double DEFAULT NULL,
  `BiasC1PosMax` double DEFAULT NULL,
  `BiasC1PosAvg` double DEFAULT NULL,
  `BiasC1PosStd` double DEFAULT NULL,
  `BiasC1Pos` text,
  `BiasC1PosTimes` text,
  `BiasC1PosTSN` int(11) DEFAULT NULL,
  `BiasC1PosBSN` int(11) DEFAULT NULL,
  `BiasC2PosMin` double DEFAULT NULL,
  `BiasC2PosMax` double DEFAULT NULL,
  `BiasC2PosAvg` double DEFAULT NULL,
  `BiasC2PosStd` double DEFAULT NULL,
  `BiasC2Pos` text,
  `BiasC2PosTimes` text,
  `BiasC2PosTSN` int(11) DEFAULT NULL,
  `BiasC2PosBSN` int(11) DEFAULT NULL,
  `DCBiasMin` double DEFAULT NULL,
  `DCBiasMax` double DEFAULT NULL,
  `DCBiasAvg` double DEFAULT NULL,
  `DCBiasStd` double DEFAULT NULL,
  `DCBias` text,
  `DCBiasTimes` text,
  `DCBiasTSN` int(11) DEFAULT NULL,
  `DCBiasBSN` int(11) DEFAULT NULL,
  `StepLogSegmentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ch3`;
CREATE TABLE `ch3` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `LotID` text,
  `MaterialName` text,
  `RecipeName` text,
  `RcpTotalStep` int(11) DEFAULT NULL,
  `RcpStepCounter` int(11) DEFAULT NULL,
  `RcpStepName` text,
  `RcpStepTime` double DEFAULT NULL,
  `RcpStepStartTime` text,
  `RcpStepElapsedTime` double DEFAULT NULL,
  `PedControlAIMin` double DEFAULT NULL,
  `PedControlAIMax` double DEFAULT NULL,
  `PedControlAIAvg` double DEFAULT NULL,
  `PedControlAIStd` double DEFAULT NULL,
  `PedControlAI` text,
  `PedControlAITimes` text,
  `PedControlAITSN` int(11) DEFAULT NULL,
  `PedControlAIBSN` int(11) DEFAULT NULL,
  `BSPMin` double DEFAULT NULL,
  `BSPMax` double DEFAULT NULL,
  `BSPAvg` double DEFAULT NULL,
  `BSPStd` double DEFAULT NULL,
  `BSP` text,
  `BSPTimes` text,
  `BSPTSN` int(11) DEFAULT NULL,
  `BSPBSN` int(11) DEFAULT NULL,
  `BSFMin` double DEFAULT NULL,
  `BSFMax` double DEFAULT NULL,
  `BSFAvg` double DEFAULT NULL,
  `BSFStd` double DEFAULT NULL,
  `BSF` text,
  `BSFTimes` text,
  `BSFTSN` int(11) DEFAULT NULL,
  `BSFBSN` int(11) DEFAULT NULL,
  `BSPSetValueMin` double DEFAULT NULL,
  `BSPSetValueMax` double DEFAULT NULL,
  `BSPSetValueAvg` double DEFAULT NULL,
  `BSPSetValueStd` double DEFAULT NULL,
  `BSPSetValue` text,
  `BSPSetValueTimes` text,
  `BSPSetValueTSN` int(11) DEFAULT NULL,
  `BSPSetValueBSN` int(11) DEFAULT NULL,
  `ForelineMin` double DEFAULT NULL,
  `ForelineMax` double DEFAULT NULL,
  `ForelineAvg` double DEFAULT NULL,
  `ForelineStd` double DEFAULT NULL,
  `Foreline` text,
  `ForelineTimes` text,
  `ForelineTSN` int(11) DEFAULT NULL,
  `ForelineBSN` int(11) DEFAULT NULL,
  `NF3Min` double DEFAULT NULL,
  `NF3Max` double DEFAULT NULL,
  `NF3Avg` double DEFAULT NULL,
  `NF3Std` double DEFAULT NULL,
  `NF3` text,
  `NF3Times` text,
  `NF3TSN` int(11) DEFAULT NULL,
  `NF3BSN` int(11) DEFAULT NULL,
  `WF6Min` double DEFAULT NULL,
  `WF6Max` double DEFAULT NULL,
  `WF6Avg` double DEFAULT NULL,
  `WF6Std` double DEFAULT NULL,
  `WF6` text,
  `WF6Times` text,
  `WF6TSN` int(11) DEFAULT NULL,
  `WF6BSN` int(11) DEFAULT NULL,
  `WF6LMin` double DEFAULT NULL,
  `WF6LMax` double DEFAULT NULL,
  `WF6LAvg` double DEFAULT NULL,
  `WF6LStd` double DEFAULT NULL,
  `WF6L` text,
  `WF6LTimes` text,
  `WF6LTSN` int(11) DEFAULT NULL,
  `WF6LBSN` int(11) DEFAULT NULL,
  `Ar1Min` double DEFAULT NULL,
  `ArEPMax` double DEFAULT NULL,
  `Ar1Max` double DEFAULT NULL,
  `Ar1Avg` double DEFAULT NULL,
  `Ar1Std` double DEFAULT NULL,
  `Ar1` text,
  `Ar1Times` text,
  `Ar1TSN` int(11) DEFAULT NULL,
  `Ar1BSN` int(11) DEFAULT NULL,
  `Ar2Min` double DEFAULT NULL,
  `Ar2Max` double DEFAULT NULL,
  `Ar2Avg` double DEFAULT NULL,
  `Ar2Std` double DEFAULT NULL,
  `Ar2` text,
  `Ar2Times` text,
  `Ar2TSN` int(11) DEFAULT NULL,
  `Ar2BSN` int(11) DEFAULT NULL,
  `B2H6Min` double DEFAULT NULL,
  `B2H6Max` double DEFAULT NULL,
  `B2H6Avg` double DEFAULT NULL,
  `B2H6Std` double DEFAULT NULL,
  `B2H6` text,
  `B2H6Times` text,
  `B2H6TSN` int(11) DEFAULT NULL,
  `B2H6BSN` int(11) DEFAULT NULL,
  `H2Min` double DEFAULT NULL,
  `H2Max` double DEFAULT NULL,
  `H2Avg` double DEFAULT NULL,
  `H2Std` double DEFAULT NULL,
  `H2` text,
  `H2Times` text,
  `H2TSN` int(11) DEFAULT NULL,
  `H2BSN` int(11) DEFAULT NULL,
  `H2EPMin` double DEFAULT NULL,
  `H2EPMax` double DEFAULT NULL,
  `H2EPAvg` double DEFAULT NULL,
  `H2EPStd` double DEFAULT NULL,
  `H2EP` text,
  `H2EPTimes` text,
  `H2EPTSN` int(11) DEFAULT NULL,
  `H2EPBSN` int(11) DEFAULT NULL,
  `DiluteMin` double DEFAULT NULL,
  `DiluteMax` double DEFAULT NULL,
  `DiluteAvg` double DEFAULT NULL,
  `DiluteStd` double DEFAULT NULL,
  `Dilute` text,
  `DiluteTimes` text,
  `DiluteTSN` int(11) DEFAULT NULL,
  `DiluteBSN` int(11) DEFAULT NULL,
  `BalanceMin` double DEFAULT NULL,
  `BalanceMax` double DEFAULT NULL,
  `BalanceAvg` double DEFAULT NULL,
  `BalanceStd` double DEFAULT NULL,
  `Balance` text,
  `BalanceTimes` text,
  `BalanceTSN` int(11) DEFAULT NULL,
  `BalanceBSN` int(11) DEFAULT NULL,
  `ArBPMin` double DEFAULT NULL,
  `ArBPMax` double DEFAULT NULL,
  `ArBPAvg` double DEFAULT NULL,
  `ArBPStd` double DEFAULT NULL,
  `ArBP` text,
  `ArBPTimes` text,
  `ArBPTSN` int(11) DEFAULT NULL,
  `ArBPBSN` int(11) DEFAULT NULL,
  `ArEPMin` double DEFAULT NULL,
  `ArEPAvg` double DEFAULT NULL,
  `ArEPStd` double DEFAULT NULL,
  `ArEP` text,
  `ArEPTimes` text,
  `ArEPTSN` int(11) DEFAULT NULL,
  `ArEPBSN` int(11) DEFAULT NULL,
  `ArSPMin` double DEFAULT NULL,
  `ArSPMax` double DEFAULT NULL,
  `ArSPAvg` double DEFAULT NULL,
  `ArSPStd` double DEFAULT NULL,
  `ArSP` text,
  `ArSPTimes` text,
  `ArSPTSN` int(11) DEFAULT NULL,
  `ArSPBSN` int(11) DEFAULT NULL,
  `TVPressureMin` double DEFAULT NULL,
  `TVPressureMax` double DEFAULT NULL,
  `TVPressureAvg` double DEFAULT NULL,
  `TVPressureStd` double DEFAULT NULL,
  `TVPressure` text,
  `TVPressureTimes` text,
  `TVPressureTSN` int(11) DEFAULT NULL,
  `TVPressureBSN` int(11) DEFAULT NULL,
  `TVAnglePosMin` double DEFAULT NULL,
  `TVAnglePosMax` double DEFAULT NULL,
  `TVAnglePosAvg` double DEFAULT NULL,
  `TVAnglePosStd` double DEFAULT NULL,
  `TVAnglePos` text,
  `TVAnglePosTimes` text,
  `TVAnglePosTSN` int(11) DEFAULT NULL,
  `TVAnglePosBSN` int(11) DEFAULT NULL,
  `WaferCounterMin` double DEFAULT NULL,
  `WaferCounterMax` double DEFAULT NULL,
  `WaferCounterAvg` double DEFAULT NULL,
  `WaferCounterStd` double DEFAULT NULL,
  `WaferCounter` text,
  `WaferCounterTimes` text,
  `WaferCounterTSN` int(11) DEFAULT NULL,
  `WaferCounterBSN` int(11) DEFAULT NULL,
  `EndPointMin` double DEFAULT NULL,
  `EndPointMax` double DEFAULT NULL,
  `EndPointAvg` double DEFAULT NULL,
  `EndPointStd` double DEFAULT NULL,
  `EndPoint` text,
  `EndPointTimes` text,
  `EndPointTSN` int(11) DEFAULT NULL,
  `EndPointBSN` int(11) DEFAULT NULL,
  `PedPosMin` double DEFAULT NULL,
  `PedPosMax` double DEFAULT NULL,
  `PedPosAvg` double DEFAULT NULL,
  `PedPosStd` double DEFAULT NULL,
  `PedPos` text,
  `PedPosTimes` text,
  `PedPosTSN` int(11) DEFAULT NULL,
  `PedPosBSN` int(11) DEFAULT NULL,
  `StepLogSegmentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cha`;
CREATE TABLE `cha` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `LotID` text,
  `MaterialName` text,
  `RecipeName` text,
  `RcpTotalStep` int(11) DEFAULT NULL,
  `RcpStepCounter` int(11) DEFAULT NULL,
  `RcpStepName` text,
  `RcpStepTime` double DEFAULT NULL,
  `RcpStepElapsedTime` double DEFAULT NULL,
  `RcpStepStartTime` text,
  `PressureMin` double DEFAULT NULL,
  `PressureMax` double DEFAULT NULL,
  `PressureAvg` double DEFAULT NULL,
  `PressureStd` double DEFAULT NULL,
  `Pressure` text,
  `PressureTimes` text,
  `PressureTSN` int(11) DEFAULT NULL,
  `PressureBSN` int(11) DEFAULT NULL,
  `StepLogSegmentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `chb`;
CREATE TABLE `chb` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `LotID` text,
  `MaterialName` text,
  `RecipeName` text,
  `RcpTotalStep` int(11) DEFAULT NULL,
  `RcpStepCounter` int(11) DEFAULT NULL,
  `RcpStepName` text,
  `RcpStepTime` double DEFAULT NULL,
  `RcpStepElapsedTime` double DEFAULT NULL,
  `RcpStepStartTime` text,
  `PressureMin` double DEFAULT NULL,
  `PressureMax` double DEFAULT NULL,
  `PressureAvg` double DEFAULT NULL,
  `PressureStd` double DEFAULT NULL,
  `Pressure` text,
  `PressureTimes` text,
  `PressureTSN` int(11) DEFAULT NULL,
  `PressureBSN` int(11) DEFAULT NULL,
  `StepLogSegmentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `chc`;
CREATE TABLE `chc` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `LotID` text,
  `MaterialName` text,
  `RecipeName` text,
  `RcpTotalStep` int(11) DEFAULT NULL,
  `RcpStepCounter` int(11) DEFAULT NULL,
  `RcpStepName` text,
  `RcpStepTime` double DEFAULT NULL,
  `RcpStepElapsedTime` double DEFAULT NULL,
  `RcpStepStartTime` text,
  `InnerPowerMin` double DEFAULT NULL,
  `InnerPowerMax` double DEFAULT NULL,
  `InnerPowerAvg` double DEFAULT NULL,
  `InnerPowerStd` double DEFAULT NULL,
  `InnerPower` text,
  `InnerPowerTimes` text,
  `InnerPowerTSN` int(11) DEFAULT NULL,
  `InnerPowerBSN` int(11) DEFAULT NULL,
  `InnerCurrentMin` double DEFAULT NULL,
  `InnerCurrentMax` double DEFAULT NULL,
  `InnerCurrentAvg` double DEFAULT NULL,
  `InnerCurrentStd` double DEFAULT NULL,
  `InnerCurrent` text,
  `InnerCurrentTimes` text,
  `InnerCurrentTSN` int(11) DEFAULT NULL,
  `InnerCurrentBSN` int(11) DEFAULT NULL,
  `OuterPowerMin` double DEFAULT NULL,
  `OuterPowerMax` double DEFAULT NULL,
  `OuterPowerAvg` double DEFAULT NULL,
  `OuterPowerStd` double DEFAULT NULL,
  `OuterPower` text,
  `OuterPowerTimes` text,
  `OuterPowerTSN` int(11) DEFAULT NULL,
  `OuterPowerBSN` int(11) DEFAULT NULL,
  `OuterCurrentMin` double DEFAULT NULL,
  `OuterCurrentMax` double DEFAULT NULL,
  `OuterCurrentAvg` double DEFAULT NULL,
  `OuterCurrentStd` double DEFAULT NULL,
  `OuterCurrent` text,
  `OuterCurrentTimes` text,
  `OuterCurrentTSN` int(11) DEFAULT NULL,
  `OuterCurrentBSN` int(11) DEFAULT NULL,
  `HeaterTempMin` double DEFAULT NULL,
  `HeaterTempMax` double DEFAULT NULL,
  `HeaterTempAvg` double DEFAULT NULL,
  `HeaterTempStd` double DEFAULT NULL,
  `HeaterTemp` text,
  `HeaterTempTimes` text,
  `HeaterTempTSN` int(11) DEFAULT NULL,
  `HeaterTempBSN` int(11) DEFAULT NULL,
  `HeaterPowerMin` double DEFAULT NULL,
  `HeaterPowerMax` double DEFAULT NULL,
  `HeaterPowerAvg` double DEFAULT NULL,
  `HeaterPowerStd` double DEFAULT NULL,
  `HeaterPower` text,
  `HeaterPowerTimes` text,
  `HeaterPowerTSN` int(11) DEFAULT NULL,
  `HeaterPowerBSN` int(11) DEFAULT NULL,
  `CGMin` double DEFAULT NULL,
  `CGMax` double DEFAULT NULL,
  `CGAvg` double DEFAULT NULL,
  `CGStd` double DEFAULT NULL,
  `CG` text,
  `CGTimes` text,
  `CGTSN` int(11) DEFAULT NULL,
  `CGBSN` int(11) DEFAULT NULL,
  `PressureMin` double DEFAULT NULL,
  `PressureMax` double DEFAULT NULL,
  `PressureAvg` double DEFAULT NULL,
  `PressureStd` double DEFAULT NULL,
  `Pressure` text,
  `PressureTimes` text,
  `PressureTSN` int(11) DEFAULT NULL,
  `PressureBSN` int(11) DEFAULT NULL,
  `StepLogSegmentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `che`;
CREATE TABLE `che` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `BiasRFForwardPowerMin` double DEFAULT NULL,
  `LotID` text,
  `MaterialName` text,
  `RecipeName` text,
  `RcpTotalStep` int(11) DEFAULT NULL,
  `RcpStepCounter` int(11) DEFAULT NULL,
  `RcpStepName` text,
  `RcpStepTime` double DEFAULT NULL,
  `RcpStepElapsedTime` double DEFAULT NULL,
  `RcpStepStartTime` text,
  `BiasRFReflectedPower` text,
  `BiasRFForwardPowerMax` double DEFAULT NULL,
  `BiasRFForwardPowerAvg` double DEFAULT NULL,
  `BiasRFForwardPowerStd` double DEFAULT NULL,
  `BiasRFForwardPower` text,
  `BiasRFForwardPowerTimes` text,
  `BiasRFForwardPowerTSN` int(11) DEFAULT NULL,
  `BiasRFForwardPowerBSN` int(11) DEFAULT NULL,
  `BiasRFReflectedPowerMin` double DEFAULT NULL,
  `BiasRFReflectedPowerMax` double DEFAULT NULL,
  `BiasRFReflectedPowerAvg` double DEFAULT NULL,
  `BiasRFReflectedPowerStd` double DEFAULT NULL,
  `BiasRFReflectedPowerTimes` text,
  `BiasRFReflectedPowerTSN` int(11) DEFAULT NULL,
  `BiasRFReflectedPowerBSN` int(11) DEFAULT NULL,
  `BiasC1PosMin` double DEFAULT NULL,
  `BiasC1PosMax` double DEFAULT NULL,
  `BiasC1PosAvg` double DEFAULT NULL,
  `BiasC1PosStd` double DEFAULT NULL,
  `BiasC1Pos` text,
  `BiasC1PosTimes` text,
  `BiasC1PosTSN` int(11) DEFAULT NULL,
  `BiasC1PosBSN` int(11) DEFAULT NULL,
  `BiasC2PosMin` double DEFAULT NULL,
  `BiasC2PosMax` double DEFAULT NULL,
  `BiasC2PosAvg` double DEFAULT NULL,
  `BiasC2PosStd` double DEFAULT NULL,
  `BiasC2Pos` text,
  `BiasC2PosTimes` text,
  `BiasC2PosTSN` int(11) DEFAULT NULL,
  `BiasC2PosBSN` int(11) DEFAULT NULL,
  `DCBiasMin` double DEFAULT NULL,
  `DCBiasMax` double DEFAULT NULL,
  `DCBiasAvg` double DEFAULT NULL,
  `DCBiasStd` double DEFAULT NULL,
  `DCBias` text,
  `DCBiasTimes` text,
  `DCBiasTSN` int(11) DEFAULT NULL,
  `DCBiasBSN` int(11) DEFAULT NULL,
  `CoilRFForwardPowerMin` double DEFAULT NULL,
  `CoilRFForwardPowerMax` double DEFAULT NULL,
  `CoilRFForwardPowerAvg` double DEFAULT NULL,
  `CoilRFForwardPowerStd` double DEFAULT NULL,
  `CoilRFForwardPower` text,
  `CoilRFForwardPowerTimes` text,
  `CoilRFForwardPowerTSN` int(11) DEFAULT NULL,
  `CoilRFForwardPowerBSN` int(11) DEFAULT NULL,
  `CoilRFReflectedPowerMin` double DEFAULT NULL,
  `CoilRFReflectedPowerMax` double DEFAULT NULL,
  `CoilRFReflectedPowerAvg` double DEFAULT NULL,
  `CoilRFReflectedPowerStd` double DEFAULT NULL,
  `CoilRFReflectedPower` text,
  `CoilRFReflectedPowerTimes` text,
  `CoilRFReflectedPowerTSN` int(11) DEFAULT NULL,
  `CoilRFReflectedPowerBSN` int(11) DEFAULT NULL,
  `CoilC1PosMin` double DEFAULT NULL,
  `CoilC1PosMax` double DEFAULT NULL,
  `CoilC1PosAvg` double DEFAULT NULL,
  `CoilC1PosStd` double DEFAULT NULL,
  `CoilC1Pos` text,
  `CoilC1PosTimes` text,
  `CoilC1PosTSN` int(11) DEFAULT NULL,
  `CoilC1PosBSN` int(11) DEFAULT NULL,
  `CoilC2PosMin` double DEFAULT NULL,
  `PedTempMax` double DEFAULT NULL,
  `CoilC2PosMax` double DEFAULT NULL,
  `CoilC2PosAvg` double DEFAULT NULL,
  `CoilC2PosStd` double DEFAULT NULL,
  `CoilC2Pos` text,
  `CoilC2PosTimes` text,
  `CoilC2PosTSN` int(11) DEFAULT NULL,
  `CoilC2PosBSN` int(11) DEFAULT NULL,
  `Ar1Min` double DEFAULT NULL,
  `Ar1Max` double DEFAULT NULL,
  `Ar1Avg` double DEFAULT NULL,
  `Ar1Std` double DEFAULT NULL,
  `Ar1` text,
  `Ar1Times` text,
  `Ar1TSN` int(11) DEFAULT NULL,
  `Ar1BSN` int(11) DEFAULT NULL,
  `Ar2Min` double DEFAULT NULL,
  `Ar2Max` double DEFAULT NULL,
  `Ar2Avg` double DEFAULT NULL,
  `Ar2Std` double DEFAULT NULL,
  `Ar2` text,
  `Ar2Times` text,
  `Ar2TSN` int(11) DEFAULT NULL,
  `Ar2BSN` int(11) DEFAULT NULL,
  `N2Min` double DEFAULT NULL,
  `N2Max` double DEFAULT NULL,
  `N2Avg` double DEFAULT NULL,
  `N2Std` double DEFAULT NULL,
  `N2` text,
  `N2Times` text,
  `N2TSN` int(11) DEFAULT NULL,
  `N2BSN` int(11) DEFAULT NULL,
  `HeMin` double DEFAULT NULL,
  `HeMax` double DEFAULT NULL,
  `HeAvg` double DEFAULT NULL,
  `HeStd` double DEFAULT NULL,
  `He` text,
  `HeTimes` text,
  `HeTSN` int(11) DEFAULT NULL,
  `HeBSN` int(11) DEFAULT NULL,
  `H2Min` double DEFAULT NULL,
  `H2Max` double DEFAULT NULL,
  `H2Avg` double DEFAULT NULL,
  `H2Std` double DEFAULT NULL,
  `H2` text,
  `H2Times` text,
  `H2TSN` int(11) DEFAULT NULL,
  `H2BSN` int(11) DEFAULT NULL,
  `ProcPressureMin` double DEFAULT NULL,
  `ProcPressureMax` double DEFAULT NULL,
  `ProcPressureAvg` double DEFAULT NULL,
  `ProcPressureStd` double DEFAULT NULL,
  `ProcPressure` text,
  `ProcPressureTimes` text,
  `ProcPressureTSN` int(11) DEFAULT NULL,
  `ProcPressureBSN` int(11) DEFAULT NULL,
  `PressureMin` double DEFAULT NULL,
  `PressureMax` double DEFAULT NULL,
  `PressureAvg` double DEFAULT NULL,
  `PressureStd` double DEFAULT NULL,
  `Pressure` text,
  `PressureTimes` text,
  `PressureTSN` int(11) DEFAULT NULL,
  `PressureBSN` int(11) DEFAULT NULL,
  `PedTempMin` double DEFAULT NULL,
  `PedTempAvg` double DEFAULT NULL,
  `PedTempStd` double DEFAULT NULL,
  `PedTemp` text,
  `PedTempTimes` text,
  `PedTempTSN` int(11) DEFAULT NULL,
  `PedTempBSN` int(11) DEFAULT NULL,
  `PendulumVlvPosMin` double DEFAULT NULL,
  `PendulumVlvPosMax` double DEFAULT NULL,
  `PendulumVlvPosAvg` double DEFAULT NULL,
  `PendulumVlvPosStd` double DEFAULT NULL,
  `PendulumVlvPos` text,
  `PendulumVlvPosTimes` text,
  `PendulumVlvPosTSN` int(11) DEFAULT NULL,
  `PendulumVlvPosBSN` int(11) DEFAULT NULL,
  `StepLogSegmentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `cjobtemp`;
CREATE TABLE `cjobtemp` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `startmode` varchar(255) NOT NULL DEFAULT '',
  `processorder` varchar(255) NOT NULL DEFAULT '',
  `pauseevent` varchar(255) DEFAULT '',
  `processjobstr` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `index_datas`;
CREATE TABLE `index_datas` (
  `full_name` varchar(128) NOT NULL,
  `aliases` text NOT NULL,
  `data_type` enum('INTDATA','STRINGDATA','DOUBLEDATA') NOT NULL,
  `access_mode` enum('READ_ONLY','READ_WRITE') NOT NULL,
  `appearance_num` int(11) NOT NULL,
  `in_tables` text NOT NULL,
  PRIMARY KEY (`full_name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `index_tables`;
CREATE TABLE `index_tables` (
  `table_name` varchar(64) NOT NULL,
  `data_num` int(11) NOT NULL,
  `datas` text NOT NULL,
  `aliases` text NOT NULL,
  PRIMARY KEY (`table_name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `jobs`;
CREATE TABLE `jobs` (
  `idx` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  `routes` longtext COLLATE utf8_bin,
  `src` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `dest` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `cyclenum` int(11) DEFAULT NULL,
  `mode` int(1) DEFAULT NULL COMMENT '1:seq,2:pip,3:con',
  `isprocess` int(1) DEFAULT NULL COMMENT '0:false,1:true',
  `isunload` int(1) DEFAULT NULL COMMENT '0:false,1:true',
  `ishigh` int(1) DEFAULT NULL COMMENT '0:false,1:true',
  `preprocess` longtext COLLATE utf8_bin,
  `createtime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modifytime` datetime DEFAULT NULL,
  `author` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `la`;
CREATE TABLE `la` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `LotID` text,
  `MaterialName` text,
  `RecipeName` text,
  `RcpTotalStep` int(11) DEFAULT NULL,
  `RcpStepCounter` int(11) DEFAULT NULL,
  `RcpStepName` text,
  `RcpStepTime` double DEFAULT NULL,
  `RcpStepElapsedTime` double DEFAULT NULL,
  `RcpStepStartTime` text,
  `RcpStepDataReport` int(11) DEFAULT NULL,
  `PressureMin` double DEFAULT NULL,
  `PressureMax` double DEFAULT NULL,
  `PressureAvg` double DEFAULT NULL,
  `PressureStd` double DEFAULT NULL,
  `Pressure` text,
  `PressureTimes` text,
  `PressureTSN` int(11) DEFAULT NULL,
  `PressureBSN` int(11) DEFAULT NULL,
  `StepLogSegmentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `lb`;
CREATE TABLE `lb` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `LotID` text,
  `MaterialName` text,
  `RecipeName` text,
  `RcpTotalStep` int(11) DEFAULT NULL,
  `RcpStepCounter` int(11) DEFAULT NULL,
  `RcpStepName` text,
  `RcpStepTime` double DEFAULT NULL,
  `RcpStepElapsedTime` double DEFAULT NULL,
  `RcpStepStartTime` text,
  `RcpStepDataReport` int(11) DEFAULT NULL,
  `PressureMin` double DEFAULT NULL,
  `PressureMax` double DEFAULT NULL,
  `PressureAvg` double DEFAULT NULL,
  `PressureStd` double DEFAULT NULL,
  `Pressure` text,
  `PressureTimes` text,
  `PressureTSN` int(11) DEFAULT NULL,
  `PressureBSN` int(11) DEFAULT NULL,
  `StepLogSegmentID` int(11) DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `lot`;
CREATE TABLE `lot` (
  `idx` bigint(20) NOT NULL AUTO_INCREMENT,
  `id` varchar(255) NOT NULL DEFAULT '',
  `jobname` varchar(255) DEFAULT NULL,
  `starttime` datetime DEFAULT NULL,
  `exectime` datetime DEFAULT NULL,
  `donetime` datetime DEFAULT NULL,
  `endtime` datetime DEFAULT NULL,
  `remark` longtext,
  `lotid` longtext,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

DROP TABLE IF EXISTS `materials`;
CREATE TABLE `materials` (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) DEFAULT '',
  `lotid` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT '',
  `curmodule` varchar(255) DEFAULT '',
  `curslot` int(11) DEFAULT NULL,
  `nextprocmodule` varchar(255) DEFAULT NULL,
  `isaligned` bit(1) DEFAULT NULL,
  `nameid` text,
  `needcooling` bit(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

DROP TABLE IF EXISTS `operations`;
CREATE TABLE `operations` (
  `optexcutor` varchar(255) NOT NULL DEFAULT '',
  `optname` varchar(255) NOT NULL DEFAULT '',
  `optstarttime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `optmodule` varchar(255) NOT NULL DEFAULT '',
  KEY `optexcutor` (`optexcutor`,`optname`,`optstarttime`,`optmodule`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `pjobtemp`;
CREATE TABLE `pjobtemp` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `startmode` varchar(255) NOT NULL DEFAULT '',
  `processroute` varchar(255) NOT NULL DEFAULT '',
  `materialtype` varchar(255) NOT NULL DEFAULT '',
  `pauseevent` varchar(255) DEFAULT NULL,
  `materials` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `pmrecipe`;
CREATE TABLE `pmrecipe` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `chamber` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `value` longtext,
  `author` varchar(255) DEFAULT '',
  `createtime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modifytime` datetime DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk;

DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `rolename` varchar(255) DEFAULT NULL,
  `FormName` varchar(40) DEFAULT '',
  `permissionstr` longtext,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk ROW_FORMAT=COMPACT;

DROP TABLE IF EXISTS `roles_old`;
CREATE TABLE `roles_old` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `rolename` varchar(255) COLLATE latin1_bin DEFAULT NULL,
  `permissiontype` varchar(40) COLLATE latin1_bin NOT NULL DEFAULT '',
  `permissionstr` longtext COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

DROP TABLE IF EXISTS `ror`;
CREATE TABLE `ror` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `chamber` text,
  `time` text,
  `ror` double DEFAULT NULL,
  `basePressure` double DEFAULT NULL,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `routes`;
CREATE TABLE `routes` (
  `idx` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  `value` longtext COLLATE utf8_bin,
  `createtime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modifytime` datetime DEFAULT NULL,
  `author` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `transfer`;
CREATE TABLE `transfer` (
  `num` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trigger_` text,
  `trigger_time` datetime DEFAULT NULL,
  `trigger_time_ms` smallint(6) DEFAULT NULL,
  `collect_time` datetime DEFAULT NULL,
  `collect_time_ms` smallint(6) DEFAULT NULL,
  `LotID` text,
  `Module` text,
  `Actor` text,
  `Action` text,
  `MaterialName` text,
  `MaterialNameID` text,
  `ActParam` text,
  `ActData` text,
  PRIMARY KEY (`num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


